### ISSUE TITLE
js1 lab1 Date plus 30 days

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/lab#88]
Den här koden ger rätt resultat.
```
/**
 * Exercise 6.2
 *
 * Create a new Date object that is equal to 'myDate' plus 30 days.  
 * 
 * Use Date.getDate and answer with the day of the month.
 *
 * Write your code below and put the answer into the variable ANSWER.
 */
var myNewDate = new Date(myDate+30);

ANSWER = myNewDate.getDate();
```

> 6.2 CORRECT. Well done!
> 3 (number)

Problemet är att koden inte alls gör rätt. Den ändrar minuter snarare än dagar.

> myDate:
> "1980-08-03T22:00:00.000Z"

> myDate+30:
> "1980-08-03T21:30:00.000Z"

Lösningen är nog så enkel som att kräva ett annat antal dagar än just 30 dagar.

**Comment by lewenhagen** [comment]
Fixed the problem, now uses randomized days, 15-25.
