### ISSUE TITLE
JavaScript labbarna har fel total i status-strängen

### ISSUE THREAD

**Issue by daniel-mmm** [dbwebb-se/lab#89]
En liten bugg med JavaScript labbarna: `Done with status 3/0/0/13 (Total/Correct/Failed/Not done).`. 3:an borde vara 13. Problemet verkar vara att `Object.keys(window.dbwebb.answers).length;` borde vara `Object.keys(window.dbwebb.answers.answers).length;`, alltså en nivå för kort in i objektet. Rad 228 i answers.html.

**Comment by mosbth** [comment]
Tacksam.
