### ISSUE TITLE
linux node1 fel på poängräkning

### ISSUE THREAD

**Issue by AndreasArne** [dbwebb-se/lab#92]
9 rätt ska ge godkänt.
15 rätt är full pott.
När jag svarar rätt på alla uppgifter får jag bara 11 poäng. Antalet poäng och uppgifter verkar stämma. Vet inte varför uträkningen blir fel.
Kan testa med koden nedanför. **Byt namn på filen till answer.js**

[answer.LOG](https://github.com/dbwebb-se/lab/files/1720095/answer.LOG)

**Comment by mosbth** [comment]
Fixade så att poängberäkningen fungerar i node-labbar, det var inte integrerat i den typen av labbar.

**Comment by mosbth** [comment]
Info här: https://dbwebb.se/forum/viewtopic.php?f=46&t=7307
